on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Git describe
        id: describe
        run: |
          echo "::set-output name=version::$(git describe --exact-match --tags 2> /dev/null || git rev-parse --short HEAD)"
      - name: Test
        id: test
        run: CGO_ENABLED=0 go test -cover ./...
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: nexus.iot.sberdevices.ru
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: nexus.iot.sberdevices.ru/${{ steps.string.outputs.lowercase }}:${{ steps.describe.outputs.version }}
          file: Dockerfile

      - name: Push
        id: push
        run: docker push nexus.iot.sberdevices.ru/${{ steps.string.outputs.lowercase }}:${{ steps.describe.outputs.version }}

      - uses: 8398a7/action-slack@v3
        with:
          channel: '#smarthome_cd'
          status: ${{ job.status }}
          fields: repo,message,commit,author,eventName # selectable (default: repo,message)
          icon_emoji: ':rocket:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always()